config/routes.rb
Rails.application.routes.draw do
  get "home", to: "home#index", as:"home"
  get "home/index"
  root :to => "home#index"
  resources :students
  resources :testcenters
  resources :highschools
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/highschool.rb
class Highschool < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :highschool
  belongs_to :testcenter
  SEX = ["Male", "Female"]
end

app/models/testcenter.rb
class Testcenter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/highschools_controller.rb
class HighschoolsController < ApplicationController
  before_action :set_highschool, only: [:show, :edit, :update, :destroy]

  # GET /highschools
  # GET /highschools.json
  def index
    @highschools = Highschool.all
  end

  # GET /highschools/1
  # GET /highschools/1.json
  def show
  end

  # GET /highschools/new
  def new
    @highschool = Highschool.new
  end

  # GET /highschools/1/edit
  def edit
  end

  # POST /highschools
  # POST /highschools.json
  def create
    @highschool = Highschool.new(highschool_params)

    respond_to do |format|
      if @highschool.save
        format.html { redirect_to @highschool, notice: 'Highschool was successfully created.' }
        format.json { render :show, status: :created, location: @highschool }
      else
        format.html { render :new }
        format.json { render json: @highschool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highschools/1
  # PATCH/PUT /highschools/1.json
  def update
    respond_to do |format|
      if @highschool.update(highschool_params)
        format.html { redirect_to @highschool, notice: 'Highschool was successfully updated.' }
        format.json { render :show, status: :ok, location: @highschool }
      else
        format.html { render :edit }
        format.json { render json: @highschool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highschools/1
  # DELETE /highschools/1.json
  def destroy
    @highschool.destroy
    respond_to do |format|
      format.html { redirect_to highschools_url, notice: 'Highschool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highschool
      @highschool = Highschool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highschool_params
      params.require(:highschool).permit(:name, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@students = Student.all
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @highschools = Highschool.all
    @testcenters = Testcenter.all
  end

  # GET /students/1/edit
  def edit
    @highschools = Highschool.all
    @testcenters = Testcenter.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :sex, :dateofbirth, :cellphonenumber, :address, :highschool_id, :testcenter_id)
    end
end

app/controllers/testcenters_controller.rb
class TestcentersController < ApplicationController
  before_action :set_testcenter, only: [:show, :edit, :update, :destroy]

  # GET /testcenters
  # GET /testcenters.json
  def index
    @testcenters = Testcenter.all
  end

  # GET /testcenters/1
  # GET /testcenters/1.json
  def show
  end

  # GET /testcenters/new
  def new
    @testcenter = Testcenter.new
  end

  # GET /testcenters/1/edit
  def edit
  end

  # POST /testcenters
  # POST /testcenters.json
  def create
    @testcenter = Testcenter.new(testcenter_params)

    respond_to do |format|
      if @testcenter.save
        format.html { redirect_to @testcenter, notice: 'Testcenter was successfully created.' }
        format.json { render :show, status: :created, location: @testcenter }
      else
        format.html { render :new }
        format.json { render json: @testcenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testcenters/1
  # PATCH/PUT /testcenters/1.json
  def update
    respond_to do |format|
      if @testcenter.update(testcenter_params)
        format.html { redirect_to @testcenter, notice: 'Testcenter was successfully updated.' }
        format.json { render :show, status: :ok, location: @testcenter }
      else
        format.html { render :edit }
        format.json { render json: @testcenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testcenters/1
  # DELETE /testcenters/1.json
  def destroy
    @testcenter.destroy
    respond_to do |format|
      format.html { redirect_to testcenters_url, notice: 'Testcenter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testcenter
      @testcenter = Testcenter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testcenter_params
      params.require(:testcenter).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highschools_helper.rb
module HighschoolsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/testcenters_helper.rb
module TestcentersHelper
end

app/views/highschools/_form.html.erb
<%= form_with(model: highschool, local: true) do |form| %>
  <% if highschool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(highschool.errors.count, "error") %> prohibited this highschool from being saved:</h2>

      <ul>
        <% highschool.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/highschools/edit.html.erb
<h1>Editing High School</h1>

<%= render 'form', highschool: @highschool %>

<%= link_to 'Show', @highschool %> |
<%= link_to 'Back', highschools_path %>

app/views/highschools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>High Schools</h1>
<%= link_to 'Home', home_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @highschools.each do |highschool| %>
      <tr>
        <td><%= highschool.name %></td>
        <td><%= highschool.address %></td>
        <td><%= link_to 'Show', highschool %></td>
        <td><%= link_to 'Edit', edit_highschool_path(highschool) %></td>
        <td><%= link_to 'Destroy', highschool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New High School', new_highschool_path %>

app/views/highschools/new.html.erb
<h1>New High School</h1>

<%= render 'form', highschool: @highschool %>

<%= link_to 'Back', highschools_path %>

app/views/highschools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @highschool.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @highschool.address %>
</p>

<%= link_to 'Edit', edit_highschool_path(@highschool) %> |
<%= link_to 'Back', highschools_path %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Home</h1>
<%= link_to 'New Student', new_student_path %> |
<%= link_to 'Show High Schools', highschools_path %> |
<%= link_to 'Show Test Centers', testcenters_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>


      <th>Cellphone Number</th>

      <th>High School</th>
      <th>Test Center</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>

        <td><%= student.cellphonenumber %></td>

        <td><%= student.highschool.name %></td>
        <td><%= student.testcenter.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Name" %>
    <%= form.text_field :name, {required: true} %>
  </div>

  <div class="field">
    <%= form.label "Sex" %>
    <%= form.select(:sex, Student::SEX) %>
  </div>

  <div class="field">
    <%= form.label "Date of Birth" %>
    <%= form.date_select :dateofbirth,  {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: Date.today.year - 100}, {required: true} %>
  </div>

  <div class="field">
    <%= form.label "Cellphone Number" %>
    <%= form.text_field :cellphonenumber %>
  </div>

  <div class="field">
    <%= form.label "Address" %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :highschool_id %>
    <%= form.select :highschool_id, options_for_select(@highschools.map{ |s| [s.name, s.id] }) %>
  </div>

  <div class="field">
    <%= form.label :testcenter_id %>
    <%= form.select :testcenter_id, options_for_select(@testcenters.map{ |s| [s.name, s.id] }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>
<%= link_to 'Home', home_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>


      <th>Cellphone Number</th>

      <th>High School</th>
      <th>Test Center</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>

        <td><%= student.cellphonenumber %></td>

        <td><%= student.highschool.name %></td>
        <td><%= student.testcenter.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @student.sex %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @student.dateofbirth %>
</p>

<p>
  <strong>Cellphone Number:</strong>
  <%= @student.cellphonenumber %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>High School:</strong>
  <%= @student.highschool.name %>
</p>

<p>
  <strong>Test Center:</strong>
  <%= @student.testcenter.name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/testcenters/_form.html.erb
<%= form_with(model: testcenter, local: true) do |form| %>
  <% if testcenter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testcenter.errors.count, "error") %> prohibited this testcenter from being saved:</h2>

      <ul>
        <% testcenter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/testcenters/edit.html.erb
<h1>Editing Test Center</h1>

<%= render 'form', testcenter: @testcenter %>

<%= link_to 'Show', @testcenter %> |
<%= link_to 'Back', testcenters_path %>

app/views/testcenters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Centers</h1>
<%= link_to 'Home', home_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testcenters.each do |testcenter| %>
      <tr>
        <td><%= testcenter.name %></td>
        <td><%= link_to 'Show', testcenter %></td>
        <td><%= link_to 'Edit', edit_testcenter_path(testcenter) %></td>
        <td><%= link_to 'Destroy', testcenter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test Center', new_testcenter_path %>

app/views/testcenters/new.html.erb
<h1>New Test Center</h1>

<%= render 'form', testcenter: @testcenter %>

<%= link_to 'Back', testcenters_path %>

app/views/testcenters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @testcenter.name %>
</p>

<%= link_to 'Edit', edit_testcenter_path(@testcenter) %> |
<%= link_to 'Back', testcenters_path %>